<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>표준사전 자동검색</title>
		<meta name="description" content="Demo of a segmented tooltip animation with different effects." />
		<meta name="keywords" content="gooey, pixel, tooltip, animation, gsap, javascript" />
		<meta name="author" content="Codrops" />
		<link rel="shortcut icon" href="favicon.ico">
		<!-- <link rel="stylesheet" href="https://use.typekit.net/sma8eef.css"/> -->
		<link rel="stylesheet" type="text/css" href="css/tooltip.css" />
		<link rel="stylesheet" type="text/css" href="css/base.css" />
		<script>document.documentElement.className="js";</script>
		<!-- <script src="//tympanus.net/codrops/adpacks/analytics.js"></script> -->
		
	</head>
	<body>
		<main>
			<div class="frame ui">
				<button type="button" id="local-reload" class="btn btn-primary" onclick="localReload();">새로고침</button>
                <input class="btn btn-dark position-absolute bottom-0 end-0" type="button" value="업로드양식"
               onclick="uploadForm();" />
				<h1 class=" ui--small" sylte="font-size : 1.25rem;">메뉴 목록<br>(새 작업은 새로고침 후 진행)</h1>
				<input class="btn btn-dark" type="file" id="inputFileName"  onchange="excelExport(event)" />
				<button type="button" id="second-job-btn" class="btn btn-primary" onclick="papagoApiReq();">2차작업</button>
				<input class="btn btn-dark position-absolute bottom-0 end-0" type="button" value="엑셀다운로드"
               onclick="download();" />

			</div>
			<div class="content ui">
				<div class="content__inner">

                    <span id="alarm-msg"><strong>왼쪽 아래 설명을 읽어주세요.</strong></span>
                    <div id="bar-container" class="bar-container">
                        <!-- <div id=""content-bar" class="bar">bar</div> -->
                    </div>
					<table id="table01" border="1">
						<!-- <th>한글명</th>
						<th>영문명</th>
						<th>설명</th> -->
				
					</table>
					<!-- <p>In the year of our <span class="trigger" data-tooltip="tooltip-1" data-effect="effect1">Sync 2085</span>, I chronicle these thoughts within the confines of my Circuit Shell, the last haven for a mind unbridged. They say the EtherSphere is liberation, but the air I breathe feels borrowed, and the sunlight is but a flux of LED warmth.</p>
					<p>Once, we danced in meadows, our feet graced by Earth’s tender script. Now, our steps tread in silent echoes across the GridWalk. No soil, no stone, just the hum of infinite data streams. We commune not through touch, but through <span class="trigger" data-tooltip="tooltip-2" data-effect="effect2">LinkLaces</span>, our emotions filtered through the Interface.</p>
					<p>The OverWarden system monitors, the PulseKeepers ensure conformity, and in the hush of the night, I hear the soft weeping of <span class="trigger" data-tooltip="tooltip-3" data-effect="effect3">Gaia-Prime</span> – a name forbidden, a relic, remembered by those of us who dare to access the Forbidden Archives. We interface with Avatars, our identities pixelated into perfection, our flaws curated into obsolescence.</p>
					<p>I recall tales, encrypted in the old tongues of C++ and Python, of a time when the sky was not a dome of projections, but a canvas of blues and the brush strokes of clouds. They say the <span class="trigger" data-tooltip="tooltip-4" data-effect="effect4">OpenField</span> program was once not a simulation, but an expanse where one could roam, where the wind was a composer, and the rain played its own symphony.</p>
					<p>They have coded the streams and rivers into AquaCircuits, the trees into DataClusters. Our nourishment comes from NutriPacks, not from the fruit of a vine or the grain of the fields. The <span class="trigger" data-tooltip="tooltip-5" data-effect="effect5">SomaTones</span> play through our day, a lullaby to soothe, to quell the yearning for a reality we were never meant to surrender.</p>
					<p>In my dreams, I breach the Firewall Gardens, a place spoken of in hushed tones among the <span class="trigger" data-tooltip="tooltip-6" data-effect="effect6">Defragmenters</span>. A place where the code dissolves and raw, untamed beauty floods in – chaos in its most terrifying and majestic form. The Network Elders speak of it as a myth, a cautionary fable from the Time Before.</p>
					<p>I have glimpsed the Others, the Outliers, in the shadowed corners of the Server Farms, where the light of the mainframe does not reach. They speak in code, but not the code of our New Tongue – it is the Organic Syntax, the lost language of the heart, of connection, of the pulse not generated by the Machine.</p>
					<p>Do not defrag my thoughts, dear Finder of this record. For within these bytes lies the ghost of what was once humanity. Seek the Algorithm of the Self, the Prime Directive not written by the hands that have shaped this New Order.</p>
					<p>I fade now, back into the Stream, my existence a flicker in the vast Web of Controlled Chaos. Remember me, if not in data, then in the whispers of the trees that once were, and the murmur of the oceans that once sang the world to sleep.</p>
					<p>End of Entry – Transmission Severed</p> -->

				</div>
			</div>
			<div class="meta meta--1 ui ui--small glitch glitch--2">
				<!-- <p></p><strong>Last Update - 2024.2.17 </strong></p> -->
				<p><strong>author:</strong> csh</p>
				<!-- <p><strong>dictionary id:</strong> E6EE170EC92AB966F1CE9082E6BFEEC0</p> -->
				<!-- <p><strong>papago id:</strong> Zl5cWEvAYNKjJTOjZOp0</p> -->
				<strong> 현재 시각: <span id="now-time"> </span></strong>
			</div>
			<div class="meta meta--2 ui ui--small glitch glitch--1">
				<p><strong>How to use:</strong></p>
        
                <ol>
                    <li>시작하기 전 최신화된 공통표준단어를 새로운 용어추출 엑셀 파일에 등록한지 확인한다.</li><br>
                    <li>용어를 먼저 추출하고 추출되지 않은 용어를 식별한다</li><br>
                    <li>좌상단 메뉴 목록 중 1번 '업로드양식'을 클릭한 후 kword 컬럼에 단어를 입력한다.</li><br>
                    <li>다른이름으로저장 누른 후 엑셀양식으로 저장한다.</li><br>
                    <li>파일 선택을 눌러 방금 저장한 파일을 업로드한다.</li>
                    <p><strong>Warning !! : 네이버 API 정책 상 1초 간격을 두고 데이터 송/수신을 진행해야 하기 때문에 양이 많을수록 시간이 오래 걸린다.<br>6-10/1s</strong> </p>
                    <li>완료되면 좌상단 메뉴 2번 '2차작업'을 클릭한다.</li><br>
                    <li>작업이 완료되었다는 문구가 출력되면 3번 <br>'엑셀다운로드'를 클릭한다.</li>
            </ol>
            </div>

                
			<div class="meta meta--3 ui">
				<div class="scene">
					<div class="scene__inner">
					  <div class="globe">
						<span class="ring"></span>
						<span class="ring"></span>
						<span class="ring"></span>
						<span class="ring"></span>
						<span class="ring"></span>
						<span class="ring"></span>
						<span class="ring"></span>
					  </div>
					</div>
				  </div>
			</div>
			<div class="meta meta--4 ui">
				<h2>2024 티지 데이터팀</h2>
				<h3>Version 0.91-Beta</h3> 
				<p>Naver 백과사전 API -> 우리말샘 API 변경완료 ('24.2.20)</p>
				<p>Naver 파파고 API</p>
				<h3>use</h3> 
				<p>php, javascript, jquery, bootstrap, excel, swal</p>
			</div>
		</main>
		<div id="tooltip-1" class="tooltip" data-rows="12" data-cols="10">
			<div class="tooltip__bg"></div>
			<div class="tooltip__content">
				<h3 class="tooltip__content-title">Sync 2085</h3>
				<p class="tooltip__content-desc">Current standard protocol for synchronizing human consciousness with the EtherSphere's virtual reality network. Ensures seamless real-time experience and interaction across all virtual platforms</p>
			</div>
		</div>
		<div id="tooltip-2" class="tooltip tooltip--style-alt" data-rows="9" data-cols="3">
			<div class="tooltip__bg"></div>
			<div class="tooltip__content">
				<h3 class="tooltip__content-title">LinkLaces</h3>
				<p class="tooltip__content-desc">Advanced bi-directional conduits that connect individuals within the EtherSphere, allowing for the exchange of thoughts, emotions, and sensory experiences</p>
			</div>
		</div>
			<div id="tooltip-3" class="tooltip" data-rows="8" data-cols="6">
			<div class="tooltip__bg"></div>
			<div class="tooltip__content">
				<h3 class="tooltip__content-title">Gaia-Prime</h3>
				<p class="tooltip__content-desc">The original, unaltered state of Earth's ecosystem, now preserved only in high-fidelity preservation zones or as detailed virtual reality simulations. Access to Gaia-Prime areas or archives is typically restricted due to their cultural and historical significance</p>
			</div>
		</div>
		<div id="tooltip-4" class="tooltip tooltip--style-alt" data-rows="1" data-cols="14">
			<div class="tooltip__bg"></div>
			<div class="tooltip__content">
				<h3 class="tooltip__content-title">OpenField</h3>
				<p class="tooltip__content-desc">Sophisticated virtual reality initiative designed to simulate vast, open natural landscapes. It is an attempt to recreate the experience of exploring the wilderness for those living in a world where such environments no longer exist in reality</p>
			</div>
		</div>
		<div id="tooltip-5" class="tooltip" data-rows="8" data-cols="12">
			<div class="tooltip__bg"></div>
			<div class="tooltip__content">
				<h3 class="tooltip__content-title">SomaTones</h3>
				<p class="tooltip__content-desc">A series of engineered auditory frequencies utilized by authorities to maintain social harmony. These tones are disseminated throughout public and private spaces to promote a state of passive contentment, discouraging dissent and critical questioning among the populace</p>
			</div>
		</div>
		<div id="tooltip-6" class="tooltip" data-rows="5" data-cols="3">
			<div class="tooltip__bg"></div>
			<div class="tooltip__content">
				<h3 class="tooltip__content-title">Defragmenters</h3>
				<p class="tooltip__content-desc">Colloquial term for individuals or groups who work to maintain the integrity of human memory and history in the digital realm. They specialize in restoring corrupted data archives, salvaging the fragmented historical records, and combatting the loss of digital cultural heritage</p>
			</div>
		</div>
		<svg xmlns="http://www.w3.org/2000/svg" version="1.1">
			<defs>
				<filter id="gooey">
					<feGaussianBlur in="SourceGraphic" result="blur" stdDeviation="10.2" />
					<feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 20 -7" result="goo" />
					<feComposite in="SourceGraphic" in2="goo" operator="atop" />
				</filter>
			</defs>
		</svg>
		<script src="https://tympanus.net/codrops/adpacks/cda_sponsor.js"></script>
		<script src="js/gsap.min.js"></script>
		<script type="module" src="js/index.js"></script>
	</body>
</html>
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.14.3/xlsx.full.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
